apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME_PLACEHOLDER
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 256Mi