apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME_PLACEHOLDER
spec:
  template:
    spec:
      containers:
      - name: app
        image: primmruuhub/devops-assignment:IMG_TAG_PLACEHOLDER