apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME_PLACEHOLDER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: app
          image: IMG_NAME:IMG_TAG_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080