name: Deploy ArgoCD to GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: devops-asm
  GKE_CLUSTER: gke-cluster 
  GKE_ZONE: asia-southeast1-b

jobs:
  deploy-argocd:
    name: deploy-argocd
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDS }}


    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl get all -A
